# Setup
setup: moco # MoCo is used here

# Model
backbone: resnet50
pretrained: ./pretrained/moco_tobacco3482_800.pth.tar
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: tobacco3482
val_db_name: tobacco3482
num_classes: 10
temperature: 0.07

# Batch size and workers
batch_size: 128
num_workers: 8

# Transformations
transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.9287, 0.9287, 0.9287]
      std: [0.1568, 0.1568, 0.1568]
