# Setup
setup: moco # MoCo is used here

# Model
backbone: resnet50
pretrained: ./pretrained/moco_hdi_5000.pth.tar
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: hdi_balanced
val_db_name: hdi_balanced
num_classes: 7
temperature: 0.07

# Batch size and workers
batch_size: 128
num_workers: 8

# Transformations
transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.7810, 0.7613, 0.7215]
      std: [0.1826, 0.1844, 0.1873]
