# Setup
setup: moco # MoCo is used here

# Model
backbone: resnet50
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: impact_full_balanced
val_db_name: impact_full_balanced
num_classes: 5
temperature: 0.07

# Batch size and workers
batch_size: 128
num_workers: 8

# Transformations
transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
