# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Weight update
update_cluster_head_only: False # Update full network in SCAN
num_heads: 1 # Only use one head

# Model
backbone: resnet50

# Dataset
train_db_name: hdi_balanced
val_db_name: hdi_balanced
num_classes: 7
num_neighbors: 20

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.7608, 0.7517, 0.7362]
      std: [0.2370, 0.2385, 0.2395]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 32
     random: True

transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.7608, 0.7517, 0.7362]
      std: [0.2370, 0.2385, 0.2395]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.00001
   weight_decay: 0.0001
epochs: 100
batch_size: 128
num_workers: 8

# Scheduler
scheduler: constant
